waffleio/waffle.io-takeout

build.sh, install.sh
connected to waffleio/waffle.io-app#852
=> proxy configuration in installation script

build.sh, install.sh, upload.sh
=> add volume mount when running docker for customer CA certificates

build.sh, install.sh
connected to waffleio/waffle.io-app#852
=> remove models, add migrations

bin/build.sh, bin/install.sh, bin/upload.sh
=> add admin tool to takeout

bin/build.sh, bin/install.sh, etc/init.d/waffle, etc/init.d/waffle-api
=> adding api to takeout

bin/install.sh, etc/init.d/waffle-nginx, etc/waffle/environment.list
Closes waffleio/waffle.io-app#1031
=> Updated install script to use a different algorithm for POXA ENVs. Closes #1031

compose/docker-compose.yml
@homeyer here's a stubbed out docker-compose for you to try out.
=> Adding base docker-compose.yml

releases/2.0.0.md
connected to waffleio/takeout-startup#2
=> release notes for newest replicated version

releases/2.x.md
connected to waffleio/waffle.io#2422
=> 2.2.1 release notes

doc/distro-specific-instructions.md
connected to waffleio/takeout-startup#14
=> CentOS 7 instructions

bin/install.sh, compose/docker-compose.yml
connect waffleio/waffle.io-takeout#95
=> rename MONGOLAB_URI to MONGODB_URI

releases/2.x.md
connect https://github.com/waffleio/waffle.io-takeout/issues/145
=> 2.3.0-changelog

INSTALL.md
connect https://github.com/waffleio/waffle.io-takeout/issues/145
- removing mongodb requirement
- removing app level ports
- instructions for backups
=> updating install docs for 2.3.0

INSTALL.md
connect https://github.com/waffleio/waffle.io-takeout/issues/157
=> point install script to our proxied version

releases/2.x.md
connect https://github.com/waffleio/waffle.io/issues/2679
=> release 2.4.2

releases/2.x.md
connect https://github.com/waffleio/waffle.io-takeout/issues/177
=> update Release notes for 2.4.3

releases/2.x.md
connect https://github.com/waffleio/waffle.io/issues/2757
=> add release notes for 2.4.6

releases/2.x.md
connect https://github.com/waffleio/waffle.io/issues/2770
=> fix mongodb published port

bin/install.sh
Pretty self-explanatory. :rocket:
=> Fix wrong indentation in install.sh

INSTALL.md, releases/2.x.md
connect https://github.com/waffleio/support/issues/116
=> add docs and release info for restoring from a snapshot

releases/2.x.md
* closes waffleio/waffle.io-takeout#190
=> Release 2.5.0

INSTALL.md
* Introducing the option for an AMI installation
* Updates our install guide with our latest available AMI's
* connect #156
=> Add ami installation

INSTALL.md
* connect waffleio/takeout-ami#3
* connect waffleio/takeout-ami#2
* connect waffleio/takeout-ami#1
=> Adds new AMI's

releases/2.x.md
* connect waffleio/waffle.io-takeout#205
=> Release notes for takeout burndown chart release
